In [6]:
import councilcount as cc

In [7]:
census_api_key = '2f42b2b59ea3d5882dd01587b2e25769f000ed56'

In [8]:
cc.available_years()

5-Year ACS Surveys available: 2007-2011, 2012-2016, 2019-2023

Note: when using `councilcount` functions, only include the end year as the input for the year variable (e.g. '2023' for the 2019-2023 survey).

In [9]:
acs_year = 2023
cc.get_available_councilcount_codes(acs_year=acs_year)

Printing data dictionary for the 2023 5-Year ACS

,estimate_var_code,estimate_description,denominator_var_code,denominator_description,acs_survey
0,B01001_001E,Total population,NaN,NaN,Detailed Tables 5-Year
1,B05005_001E,Entered the U.S. after birth,B01001_001E,Total population,Detailed Tables 5-Year
2,B05005_002E,Entered U.S. 2010 or later,B05005_001E,Entered the U.S. after birth,Detailed Tables 5-Year
3,B05005_007E,Entered U.S. 2000 to 2009,B05005_001E,Entered the U.S. after birth,Detailed Tables 5-Year
4,B05005_012E,Entered U.S. 1990 to 1999,B05005_001E,Entered the U.S. after birth,Detailed Tables 5-Year
...,...,...,...,...,...
189,DP05_0084E,"American Indian and Alaska Native alone, not H...",DP02_0088E,Total population,Data Profiles 5-Year
190,DP05_0085E,"Asian alone, not Hispanic or Latino",DP02_0088E,Total population,Data Profiles 5-Year
191,DP05_0086E,Native Hawaiian and Other Pacific Islander alo...,DP02_0088E,Total population,Data Profiles 5-Year
192,DP05_0087E,"Some other race alone, not Hispanic or Latino",DP02_0088E,Total population,Data Profiles 5-Year
193,DP05_0088E,"Two or more races, not Hispanic or Latino",DP02_0088E,Total population,Data Profiles 5-Year

In [21]:
acs_year = 2011
survey_key = '3'
demo_dict = {
    "S0101_C01_004E":'person'
    # "B01001A_003E":'person'
    # "DP02_0002E": "household", # Married-couple household
    # "DP02_0025E": "person", # Males 15 and over
    # "DP02_0026E": "person" # Never married males 15 and over
}
geo = "nta" # "councildist", "policeprct", "schooldist", "nta", "communitydist", "modzcta", "borough", and "city" are acceptable inputs
total_pop_code = 'S0101_C01_001E'#"B01001_001E" #"DP02_0088E"# # Use this Data Profiles code for years 2020 and above. Use "DP02_0086E" for 2018 and earlier surveys. Use "DP02_0087E" for 2019. For Detailed Tables, use "B01001_001E" for all years. For Subject Tables, use "S0101_C01_001E" for all years.
total_house_code = None#"DP02_0001E" # This code should be correct for all years of Data Profiles. For Detailed Tables, use "B19001_001E" for all years. For Subject Tables, use "S1901_C01_001E" for all years.
    
table = cc.generate_new_estimates(survey_key=survey_key, acs_year=acs_year, demo_dict=demo_dict, geo=geo, census_api_key=census_api_key, total_pop_code=total_pop_code, total_house_code=total_house_code, boundary_year=2013)
table

/Users/RAvram/.pyenv/versions/3.9.17/lib/python3.9/site-packages/councilcount/estimates.py:1072: UserWarning: `boundary_year` is only relevant for `geo = councildist`. Ignoring `boundary_year` input.
  warn("`boundary_year` is only relevant for `geo = councildist`. Ignoring `boundary_year` input.")

KeyError: 'S0101_C01_004M'

In [ ]:
var_codes = [
"DP05_0003E", # Female
"DP02_0065E" # Adults with Bachelorâ€™s degree or higher
]
geo = "modzcta" # "councildist", "policeprct", "schooldist", "nta", "communitydist", "modzcta", "borough", and "city" are acceptable inputs
boundary_year = '2023' # only necessary for Council District requestsâ€”2013 and 2023 are accetable inputs

cc.get_councilcount_estimates(acs_year=acs_year, geo=geo, var_codes=var_codes, boundary_year=boundary_year)

/Users/RAvram/.pyenv/versions/3.9.17/lib/python3.9/site-packages/councilcount/estimates.py:1253: UserWarning: `boundary_year` is only relevant for `geo = councildist`. Ignoring `boundary_year` input.
  warn("`boundary_year` is only relevant for `geo = councildist`. Ignoring `boundary_year` input.")

,modzcta,DP05_0003E,DP05_0003M,DP05_0003PE,DP05_0003PM,DP05_0003V,DP02_0065E,DP02_0065M,DP02_0065PE,DP02_0065PM,DP02_0065V
0,10001,15010.0,1357.0,51.62,3.42,5.50,9424.0,1009.0,41.47,3.64,6.51
1,10002,37407.0,1962.0,49.53,1.53,3.19,15771.0,1236.0,26.54,1.76,4.76
2,10003,27418.0,2112.0,50.94,2.92,4.68,16346.0,2279.0,44.73,5.23,8.48
3,10004,1757.0,483.0,45.34,6.40,16.71,1283.0,392.0,42.62,9.13,18.57
4,10005,4601.0,761.0,49.81,6.09,10.05,3703.0,658.0,50.55,6.52,10.80
...,...,...,...,...,...,...,...,...,...,...,...
173,11692,12206.0,1012.0,52.51,1.21,5.04,2411.0,467.0,16.31,2.98,11.77
174,11693,7573.0,994.0,57.96,4.99,7.98,2048.0,393.0,21.92,3.65,11.67
175,11694,11115.0,1152.0,51.87,3.49,6.30,3479.0,504.0,22.52,2.87,8.81
176,11697,2190.0,300.0,53.12,12.51,8.33,827.0,220.0,26.87,5.05,16.17
177,99999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
year = 2011
cc.get_bbl_population_estimates(year=year)

Printing BBL population estimates for 2011

       borough   block   lot   latitude  longitude  bbl_population_estimate
0           BK     1.0  50.0  40.704620 -73.987059                 0.000000
1           BK     6.0   1.0  40.704760 -73.980181                 0.000000
2           BK     7.0   1.0  40.704604 -73.989086                 0.000000
3           BK     7.0  21.0  40.704110 -73.989303                 0.000000
4           BK    12.0   1.0  40.704532 -73.981757                 0.000000
...        ...     ...   ...        ...        ...                      ...
852277      SI  8050.0  83.0  40.509152 -74.250189                 2.720023
852278      SI  8050.0  86.0  40.508963 -74.250274                 2.720023
852279      SI  8050.0  89.0  40.508834 -74.250187                 2.720023
852280      SI  8050.0  92.0  40.508794 -74.249856                 2.720023
852281      SI  8050.0  94.0  40.508701 -74.249673                 2.720023

[852282 rows x 6 columns]

In [18]:
acs_year = 2011
survey_key='3'
census_api_key = "2f42b2b59ea3d5882dd01587b2e25769f000ed56"
cc.get_census_api_codes(survey_key=survey_key, acs_year=acs_year, census_api_key=census_api_key)

         variable_code                               variable_description
0            LSAD_NAME            Legal/Statistical Area Description name
1       S0101_C01_001E                  Total!!Estimate!!Total population
2       S0101_C01_002E                Total!!Estimate!!AGE!!Under 5 years
3       S0101_C01_003E                 Total!!Estimate!!AGE!!5 to 9 years
4       S0101_C01_004E               Total!!Estimate!!AGE!!10 to 14 years
...                ...                                                ...
11522  S2601B_C05_104E  College/university housing!!Estimate!!With ear...
11523  S2601B_C05_105E  College/university housing!!Estimate!!With ear...
11524  S2601B_C05_106E  College/university housing!!Estimate!!With ear...
11525  S2601B_C05_107E  College/university housing!!Estimate!!With ear...
11526  S2601B_C05_108E  College/university housing!!Estimate!!With Foo...

[11527 rows x 2 columns]

In [ ]:
import inspect
import councilcount

print(inspect.getfile(councilcount.get_census_api_codes))
print(inspect.getsource(councilcount.get_census_api_codes))

/Users/RAvram/.pyenv/versions/3.9.17/lib/python3.9/site-packages/councilcount/estimates.py
def get_census_api_codes(survey_key, acs_year, census_api_key):

    """

    This function pulls from an American Community Survey (ACS) 5-Year data dictionary to show all variable
    codes for a given year, including those beyond the existing CouncilCount database. Each variable code represents a demographic
    estimate provided by the ACS, which can be accessed via an API. Visit
    https://api.census.gov/data/<INSERT ACS YEAR>/acs/acs5.html and click "variables" for the desired survey to view the options in web format.

    Parameters:
    -----------
    survey_key : str
        Code indicating which ACS 5-Year survey the requested variables come from.
        - Key:
            '1': Detailed Tables
            '2': Data Profiles
            '3': Subject Tables
    acs_year : int/str
        The 5-Year ACS end-year to fetch data for (e.g., 2022 for the 2018-2022 ACS).
    census_api_key : str
        API key for accessing the U.S. Census Bureau's API.

    Returns:
    --------
        DataFrame: A table with 'variable_code' and 'variable_description' columns.

    Notes:
    ------
        - This function pulls directly from https://api.census.gov/data/<INSERT ACS YEAR>/acs/acs5/<UNIQUE SURVEY URL>/variables.html.
        - These variable codes may be used as inputs for councilcount functions that generate new estimates, like
        `generate_new_estimates()`.
        - To view the variables that are currently covered by the CouncilCount database, use `get_available_councilcount_codes()`.
        If the desired variable is on this list, you may use `get_councilcount_estimates()` instead of `generate_new_estimates()`.

    """

    # preparing url

    # define parameters
    base_url = "https://api.census.gov/data"
    dataset = surveys[survey_key] # ACS 5-year dataset

    base_url = f'{base_url}/{acs_year}/acs/acs5{dataset}/variables?key={census_api_key}'

    response = requests.get(base_url)
    response.raise_for_status()
    data = response.json()

    acs_dict = {}

    for d in data: # putting all code/ description pairs in a dict

        # all codes have '_' in them
        # removing any entries that aren't an estimate census codes (must end in 'E')
        # also removing codes for Puerto Rico

        if (('_' in d[0]) and (d[0].endswith('E'))) and ('PR' not in d[0]) and (d[0][-2:] != 'PE'):

            acs_dict.update({d[0]:d[1]})

    acs_code_df = pd.DataFrame([acs_dict]).melt(var_name="variable_code",
                                                value_name="variable_description").sort_values('variable_code')
    acs_code_df = acs_code_df.reset_index().drop(columns=['index']) # cleaning index

    return acs_code_df

In [ ]:
demo_dict = {
    "DP02_0002E": "household", # Married-couple household
    "DP02_0025E": "person", # Males 15 and over
    "DP02_0026E": "person" # Never married males 15 and over
    }
geo = "schooldist" # "councildist", "policeprct", "schooldist", "nta", "communitydist", "modzcta", "borough", and "city" are acceptable inputs
total_pop_code = "DP02_0088E" # Use this Data Profiles code for years 2020 and above. Use "DP02_0086E" for 2018 and earlier surveys. Use "DP02_0087E" for 2019. For Detailed Tables, use "B01001_001E" for all years. For Subject Tables, use "S0101_C01_001E" for all years.
total_house_code = "DP02_0001E" # This code should be correct for all years of Data Profiles. For Detailed Tables, use "B19001_001E" for all years. For Subject Tables, use "S1901_C01_001E" for all years.
    
table = cc.generate_new_estimates(survey_key='2', acs_year=acs_year, demo_dict=demo_dict, geo=geo, census_api_key=census_api_key, total_pop_code=total_pop_code, total_house_code=total_house_code, boundary_year=None).head()

In [ ]:
table

,schooldist,DP02_0001E,DP02_0001M,DP02_0001V,DP02_0002E,DP02_0002M,DP02_0002V,DP02_0025E,DP02_0025M,DP02_0025V,DP02_0026E,DP02_0026M,DP02_0026V,DP02_0088E,DP02_0088M,DP02_0088V,school_dist
0,1,64543.0,1852.0,1.74,12134.0,1052.0,5.27,52835.0,1834.0,2.11,33274.0,1798.0,3.28,119844.0,4099.0,2.08,1
1,2,512585.0,6817.0,0.81,157326.0,4101.0,1.58,350164.0,5173.0,0.90,170017.0,4526.0,1.62,808229.0,11558.0,0.87,2
2,3,157053.0,3549.0,1.37,53216.0,2167.0,2.48,114756.0,3194.0,1.69,51469.0,2302.0,2.72,287640.0,7799.0,1.65,3
3,4,43209.0,1521.0,2.14,7623.0,700.0,5.58,34398.0,1516.0,2.68,21360.0,1405.0,4.00,92464.0,3782.0,2.49,4
4,5,68942.0,1620.0,1.43,12558.0,938.0,4.54,56701.0,1795.0,1.92,34780.0,1708.0,2.99,145971.0,4379.0,1.82,5